/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SoberJourneyFHE {
  export type JourneyStruct = {
    journeyId: BigNumberish;
    creator: AddressLike;
    journeyCID: string;
    startTime: BigNumberish;
    endTime: BigNumberish;
    daysTotal: BigNumberish;
    stakeAmount: BigNumberish;
    stakeToken: AddressLike;
    requireEvidence: boolean;
    verificationMode: BigNumberish;
    rewardPool: BigNumberish;
    finalized: boolean;
  };

  export type JourneyStructOutput = [
    journeyId: bigint,
    creator: string,
    journeyCID: string,
    startTime: bigint,
    endTime: bigint,
    daysTotal: bigint,
    stakeAmount: bigint,
    stakeToken: string,
    requireEvidence: boolean,
    verificationMode: bigint,
    rewardPool: bigint,
    finalized: boolean
  ] & {
    journeyId: bigint;
    creator: string;
    journeyCID: string;
    startTime: bigint;
    endTime: bigint;
    daysTotal: bigint;
    stakeAmount: bigint;
    stakeToken: string;
    requireEvidence: boolean;
    verificationMode: bigint;
    rewardPool: bigint;
    finalized: boolean;
  };

  export type ParticipantRecordStruct = {
    participant: AddressLike;
    enrolledAt: BigNumberish;
    status: BigNumberish;
    stakeLocked: BigNumberish;
    encryptedProgressDays: BytesLike;
  };

  export type ParticipantRecordStructOutput = [
    participant: string,
    enrolledAt: bigint,
    status: bigint,
    stakeLocked: bigint,
    encryptedProgressDays: string
  ] & {
    participant: string;
    enrolledAt: bigint;
    status: bigint;
    stakeLocked: bigint;
    encryptedProgressDays: string;
  };
}

export interface SoberJourneyFHEInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimRewards"
      | "confidentialProtocolId"
      | "enrollInJourney"
      | "finalizeJourney"
      | "getEncryptedProgressDays"
      | "getJourneyInfo"
      | "getParticipantInfo"
      | "journeys"
      | "nextJourneyId"
      | "participants"
      | "recordProgress"
      | "startJourney"
      | "validateProgress"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "JourneyFinalized"
      | "JourneyStarted"
      | "ParticipantEnrolled"
      | "ParticipantFailed"
      | "ProgressRecorded"
      | "ProgressValidated"
      | "RewardsClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enrollInJourney",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeJourney",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedProgressDays",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getJourneyInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipantInfo",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "journeys",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextJourneyId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "participants",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordProgress",
    values: [BigNumberish, string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startJourney",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      boolean,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validateProgress",
    values: [BigNumberish, AddressLike, BigNumberish, boolean, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enrollInJourney",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeJourney",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedProgressDays",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getJourneyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipantInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "journeys", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextJourneyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "participants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startJourney",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateProgress",
    data: BytesLike
  ): Result;
}

export namespace JourneyFinalizedEvent {
  export type InputTuple = [
    journeyId: BigNumberish,
    rewardPool: BigNumberish,
    winnersCount: BigNumberish
  ];
  export type OutputTuple = [
    journeyId: bigint,
    rewardPool: bigint,
    winnersCount: bigint
  ];
  export interface OutputObject {
    journeyId: bigint;
    rewardPool: bigint;
    winnersCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JourneyStartedEvent {
  export type InputTuple = [
    journeyId: BigNumberish,
    creator: AddressLike,
    journeyCID: string
  ];
  export type OutputTuple = [
    journeyId: bigint,
    creator: string,
    journeyCID: string
  ];
  export interface OutputObject {
    journeyId: bigint;
    creator: string;
    journeyCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParticipantEnrolledEvent {
  export type InputTuple = [journeyId: BigNumberish, participant: AddressLike];
  export type OutputTuple = [journeyId: bigint, participant: string];
  export interface OutputObject {
    journeyId: bigint;
    participant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParticipantFailedEvent {
  export type InputTuple = [
    journeyId: BigNumberish,
    participant: AddressLike,
    evidenceCID: string
  ];
  export type OutputTuple = [
    journeyId: bigint,
    participant: string,
    evidenceCID: string
  ];
  export interface OutputObject {
    journeyId: bigint;
    participant: string;
    evidenceCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProgressRecordedEvent {
  export type InputTuple = [
    journeyId: BigNumberish,
    participant: AddressLike,
    dayIndex: BigNumberish,
    reportCID: string
  ];
  export type OutputTuple = [
    journeyId: bigint,
    participant: string,
    dayIndex: bigint,
    reportCID: string
  ];
  export interface OutputObject {
    journeyId: bigint;
    participant: string;
    dayIndex: bigint;
    reportCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProgressValidatedEvent {
  export type InputTuple = [
    journeyId: BigNumberish,
    participant: AddressLike,
    dayIndex: BigNumberish,
    validator: AddressLike,
    approve: boolean
  ];
  export type OutputTuple = [
    journeyId: bigint,
    participant: string,
    dayIndex: bigint,
    validator: string,
    approve: boolean
  ];
  export interface OutputObject {
    journeyId: bigint;
    participant: string;
    dayIndex: bigint;
    validator: string;
    approve: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsClaimedEvent {
  export type InputTuple = [
    journeyId: BigNumberish,
    participant: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    journeyId: bigint,
    participant: string,
    amount: bigint
  ];
  export interface OutputObject {
    journeyId: bigint;
    participant: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SoberJourneyFHE extends BaseContract {
  connect(runner?: ContractRunner | null): SoberJourneyFHE;
  waitForDeployment(): Promise<this>;

  interface: SoberJourneyFHEInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimRewards: TypedContractMethod<
    [journeyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  enrollInJourney: TypedContractMethod<
    [journeyId: BigNumberish],
    [void],
    "payable"
  >;

  finalizeJourney: TypedContractMethod<
    [journeyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEncryptedProgressDays: TypedContractMethod<
    [journeyId: BigNumberish, participant: AddressLike],
    [string],
    "view"
  >;

  getJourneyInfo: TypedContractMethod<
    [journeyId: BigNumberish],
    [SoberJourneyFHE.JourneyStructOutput],
    "view"
  >;

  getParticipantInfo: TypedContractMethod<
    [journeyId: BigNumberish, participant: AddressLike],
    [SoberJourneyFHE.ParticipantRecordStructOutput],
    "view"
  >;

  journeys: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        bigint,
        bigint,
        boolean
      ] & {
        journeyId: bigint;
        creator: string;
        journeyCID: string;
        startTime: bigint;
        endTime: bigint;
        daysTotal: bigint;
        stakeAmount: bigint;
        stakeToken: string;
        requireEvidence: boolean;
        verificationMode: bigint;
        rewardPool: bigint;
        finalized: boolean;
      }
    ],
    "view"
  >;

  nextJourneyId: TypedContractMethod<[], [bigint], "view">;

  participants: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, bigint, bigint, string] & {
        participant: string;
        enrolledAt: bigint;
        status: bigint;
        stakeLocked: bigint;
        encryptedProgressDays: string;
      }
    ],
    "view"
  >;

  recordProgress: TypedContractMethod<
    [
      journeyId: BigNumberish,
      reportCID: string,
      encIncrement: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  startJourney: TypedContractMethod<
    [
      journeyCID: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      daysTotal: BigNumberish,
      stakeAmount: BigNumberish,
      stakeToken: AddressLike,
      requireEvidence: boolean,
      verificationMode: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  validateProgress: TypedContractMethod<
    [
      journeyId: BigNumberish,
      participant: AddressLike,
      dayIndex: BigNumberish,
      approve: boolean,
      evidenceCID: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[journeyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "enrollInJourney"
  ): TypedContractMethod<[journeyId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "finalizeJourney"
  ): TypedContractMethod<[journeyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEncryptedProgressDays"
  ): TypedContractMethod<
    [journeyId: BigNumberish, participant: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJourneyInfo"
  ): TypedContractMethod<
    [journeyId: BigNumberish],
    [SoberJourneyFHE.JourneyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getParticipantInfo"
  ): TypedContractMethod<
    [journeyId: BigNumberish, participant: AddressLike],
    [SoberJourneyFHE.ParticipantRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "journeys"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        bigint,
        bigint,
        boolean
      ] & {
        journeyId: bigint;
        creator: string;
        journeyCID: string;
        startTime: bigint;
        endTime: bigint;
        daysTotal: bigint;
        stakeAmount: bigint;
        stakeToken: string;
        requireEvidence: boolean;
        verificationMode: bigint;
        rewardPool: bigint;
        finalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextJourneyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "participants"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, bigint, bigint, string] & {
        participant: string;
        enrolledAt: bigint;
        status: bigint;
        stakeLocked: bigint;
        encryptedProgressDays: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordProgress"
  ): TypedContractMethod<
    [
      journeyId: BigNumberish,
      reportCID: string,
      encIncrement: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startJourney"
  ): TypedContractMethod<
    [
      journeyCID: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      daysTotal: BigNumberish,
      stakeAmount: BigNumberish,
      stakeToken: AddressLike,
      requireEvidence: boolean,
      verificationMode: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "validateProgress"
  ): TypedContractMethod<
    [
      journeyId: BigNumberish,
      participant: AddressLike,
      dayIndex: BigNumberish,
      approve: boolean,
      evidenceCID: string
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "JourneyFinalized"
  ): TypedContractEvent<
    JourneyFinalizedEvent.InputTuple,
    JourneyFinalizedEvent.OutputTuple,
    JourneyFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "JourneyStarted"
  ): TypedContractEvent<
    JourneyStartedEvent.InputTuple,
    JourneyStartedEvent.OutputTuple,
    JourneyStartedEvent.OutputObject
  >;
  getEvent(
    key: "ParticipantEnrolled"
  ): TypedContractEvent<
    ParticipantEnrolledEvent.InputTuple,
    ParticipantEnrolledEvent.OutputTuple,
    ParticipantEnrolledEvent.OutputObject
  >;
  getEvent(
    key: "ParticipantFailed"
  ): TypedContractEvent<
    ParticipantFailedEvent.InputTuple,
    ParticipantFailedEvent.OutputTuple,
    ParticipantFailedEvent.OutputObject
  >;
  getEvent(
    key: "ProgressRecorded"
  ): TypedContractEvent<
    ProgressRecordedEvent.InputTuple,
    ProgressRecordedEvent.OutputTuple,
    ProgressRecordedEvent.OutputObject
  >;
  getEvent(
    key: "ProgressValidated"
  ): TypedContractEvent<
    ProgressValidatedEvent.InputTuple,
    ProgressValidatedEvent.OutputTuple,
    ProgressValidatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsClaimed"
  ): TypedContractEvent<
    RewardsClaimedEvent.InputTuple,
    RewardsClaimedEvent.OutputTuple,
    RewardsClaimedEvent.OutputObject
  >;

  filters: {
    "JourneyFinalized(uint256,uint256,uint256)": TypedContractEvent<
      JourneyFinalizedEvent.InputTuple,
      JourneyFinalizedEvent.OutputTuple,
      JourneyFinalizedEvent.OutputObject
    >;
    JourneyFinalized: TypedContractEvent<
      JourneyFinalizedEvent.InputTuple,
      JourneyFinalizedEvent.OutputTuple,
      JourneyFinalizedEvent.OutputObject
    >;

    "JourneyStarted(uint256,address,string)": TypedContractEvent<
      JourneyStartedEvent.InputTuple,
      JourneyStartedEvent.OutputTuple,
      JourneyStartedEvent.OutputObject
    >;
    JourneyStarted: TypedContractEvent<
      JourneyStartedEvent.InputTuple,
      JourneyStartedEvent.OutputTuple,
      JourneyStartedEvent.OutputObject
    >;

    "ParticipantEnrolled(uint256,address)": TypedContractEvent<
      ParticipantEnrolledEvent.InputTuple,
      ParticipantEnrolledEvent.OutputTuple,
      ParticipantEnrolledEvent.OutputObject
    >;
    ParticipantEnrolled: TypedContractEvent<
      ParticipantEnrolledEvent.InputTuple,
      ParticipantEnrolledEvent.OutputTuple,
      ParticipantEnrolledEvent.OutputObject
    >;

    "ParticipantFailed(uint256,address,string)": TypedContractEvent<
      ParticipantFailedEvent.InputTuple,
      ParticipantFailedEvent.OutputTuple,
      ParticipantFailedEvent.OutputObject
    >;
    ParticipantFailed: TypedContractEvent<
      ParticipantFailedEvent.InputTuple,
      ParticipantFailedEvent.OutputTuple,
      ParticipantFailedEvent.OutputObject
    >;

    "ProgressRecorded(uint256,address,uint256,string)": TypedContractEvent<
      ProgressRecordedEvent.InputTuple,
      ProgressRecordedEvent.OutputTuple,
      ProgressRecordedEvent.OutputObject
    >;
    ProgressRecorded: TypedContractEvent<
      ProgressRecordedEvent.InputTuple,
      ProgressRecordedEvent.OutputTuple,
      ProgressRecordedEvent.OutputObject
    >;

    "ProgressValidated(uint256,address,uint256,address,bool)": TypedContractEvent<
      ProgressValidatedEvent.InputTuple,
      ProgressValidatedEvent.OutputTuple,
      ProgressValidatedEvent.OutputObject
    >;
    ProgressValidated: TypedContractEvent<
      ProgressValidatedEvent.InputTuple,
      ProgressValidatedEvent.OutputTuple,
      ProgressValidatedEvent.OutputObject
    >;

    "RewardsClaimed(uint256,address,uint256)": TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
    RewardsClaimed: TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
  };
}
